// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzkisvsrrwkbdytrwlsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6a2lzdnNycndrYmR5dHJ3bHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzE5NjMsImV4cCI6MjA3MDAwNzk2M30.FDnJR5cVC-MaJEPjnSIDljFrGuahk4Vfs3Z6o2WQcvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});